config/routes.rb
Rails.application.routes.draw do
  
  root :to => "notes#index"

  get 'home/index'

  devise_for :users
  resources :notes 
  resources :groups
  resources :profiles

end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/kadai2.rb
class Kadai2 < ActiveRecord::Base
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to @group
    else
      render :edit
    end
  end
 
  def edit
    @group = Group.find(params[:id])
  end

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to @group
    else
      render :new
    end
  end

  def group_params
    params.require(:group).permit(:name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :authenticate_user! 

  def index
  end
end

app/controllers/kadai2_controller.rb
class Kadai2Controller < ApplicationController
end

app/controllers/kadai2s_controller.rb
class Kadai2sController < ApplicationController
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to notes_path
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      redirect_to @note
    else
      render :edit
    end 
  end

  def edit
    @note = Note.find(params[:id])
     end
  
  def index
    @notes= Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end
  
  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to @note
    else
      render :new
    end
  end

  def note_params
    params.require(:note).permit(:title, :body, :date)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy
    redirect_to profiles_path
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to @profile
    else
      render :edit
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save 
      redirect_to @profile
    else
      render :new
    end
  end

  def profile_params
    params.require(:profile).permit(:name, :avatar)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kadai2_helper.rb
module Kadai2Helper
end

app/helpers/kadai2s_helper.rb
module Kadai2sHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/groups/edit.html.erb
<h1>New Group</h1>
<p>Edit Edit!</p>
<%= form_for(@group) do |f| %>

  <h3><%= f.label :name %></h3>
  <%= f.text_field :name, class: "form-control"%>

  <br>
  <%= f.submit "更新" %>
<% end %>

app/views/groups/index.html.erb
<h1><p class="text-success">Listing groups</p></h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.id %></td>
        <td><%= link_to 'Show', group_path(group.id) %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data:{ confirm:'本当に削除していいですか？'}%></td>
      </tr>


    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_group_path %>
 

app/views/groups/new.html.erb
<h1>New group</h1>

<%= form_for(@group) do |f| %>
  <h3><%= f.label :name %></h3>
  <%= f.text_field :name, class: "form-control"  %>
  <br>

  <%= f.submit "Create Group", :class=> "btn btn-warning" %>
<% end %>

app/views/groups/show.html.erb
<h3>Name</h3>
<%= @group.name %>

<blockquote>
  <p>YAY YAY YAY YAY</p>
  <footer>By <cite title="Source Title">Itsuko Yamamoto</cite></footer>
</blockquote>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catalengineer2014</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>

  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% end %>

</html>

app/views/notes/edit.html.erb
<h1>New Note</h1>
<p class="bg-primary">Edit your Note!</p>

<%= form_for(@note) do |f| %>
  
  <h3><%= f.label :date %></h3>
  <%= f.date_select :date %>

  <h3><%= f.label :title %></h3>
  <%= f.text_field :title, class: "form-control"%>

  <h3><%= f.label :body %></h3>
  <%= f.text_area :body %>

  <br>
  <%= f.submit "更新" %>
<% end %>

app/views/notes/index.html.erb
<h1>Listing Notes</h1>
<p class="bg-info">Hello!</p>
<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>date</th>
      <th>title</th>
      <th>body</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.id %></td>
        <td><%= note.date.strftime('%Y-%m-%d') %></td>
        <td><%= note.title %></td>
        <td><%= note.body.html_safe %></td>
        <td><%= link_to 'Show', note_path(note.id) %></td>
        
        <td><%= link_to 'Edit', edit_note_path(note) %></td>

        <td><%= link_to 'Destroy', note, method: :delete, data:{ confirm:'本当に削除していいですか？'}%></td>
     </tr>
   <% end %>
  </tbody>
</table>

    <%= link_to "New", new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= form_for(@note) do |f| %>
  
  <h3><%= f.label :date %></h3>
  <%# DateTime.now.strftime('%Y-%m-%d') %>
  <%= f.date_select :date %>

  <h3><%= f.label :title %></h3>
  <%= f.text_field :title, class: "form-control"%>

  <h3><%= f.label :body %></h3>
  <%= f.text_area :body %>

  <br>
  <%= f.submit "作成", :class => "btn btn-primary" %>
<% end %>

app/views/notes/show.html.erb
<h3>Title</h3>
<%= @note.title %>

<h3>Date</h3>
<%= @note.date.strftime('%Y-%m-%d') %>

<h3>Body</h3>
<%= @note.body.html_safe %>

<blockquote>
  <p>GOOD JOB!</p>
</blockquote>

<br>

app/views/profiles/edit.html.erb
<h1>New Profile</h1>
<p class="bg-warning">Edit Page</p>
<%= form_for(@profile) do |f| %>
  
  <h3><%= f.label :name %></h3>
  <%= f.text_field :name, class: "form-control" %>

  <h3><%= f.label :avatar %></h3>
  <%= f.text_field :avatar, class: "form-control"%>

  <br>
  <%= f.submit "更新" %>
<% end %>

app/views/profiles/index.html.erb
<h1><p class="text-warning">Listing profiles</p> <small>hello<small></h1>

<table>
  <thead>
    <tr>

      <th>Name</th>
      <th>Avatar</th>
 
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
 <tr>
        <td><%= profile.id %></td>
        <td><%= link_to 'Show', profile_path(profile.id) %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data:{ confirm:'本当に削除していいですか？'}%></td>
      </tr>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.avatar %></td>
      </tr>

    <% end %>
  </tbody>
</table>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= form_for(@profile) do |f| %>
  <h3><%= f.label :name %></h3>
  <%= f.text_field :name, class: "form-control" %>

  <h3><%= f.label :avatar %></h3>
  <%= f.text_field :avatar, class: "form-control"%>


  <br>
  <%= f.submit "Create Profile", :class=> "btn btn-success" %>
<% end %>

app/views/profiles/show.html.erb
<h3>Name</h3>
<%= @profile.name %>

<h3>Avatar</h3>
<%= @profile.avatar %>

<blockquote class="blockquote-reverse">
  <p>Hello</p> 
<footer>By <cite title="Source Title">Itsuko</cite>
</footer> 
</blockquote>

<br>